const constants = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  // TRANSACTION
  SET_TRANSACTION: "SET_TRANSACTION",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  ADD_TRANSACTION: "ADD_TRANSACTION",
  // BANKS
  SET_BANKS: "SET_BANKS",
}
export default constants
